# These are supported funding model platforms

github: MateusRodCosta
ko_fi: mateusrodcosta
liberapay: mateusrodcosta
custom: ["https://mateusrodcosta.dev/donate/", "https://mateusrodcosta.dev/pt-br/doar/"]
