[versions]
androidGradlePlugin = "8.1.2"
kotlinVersion = "1.9.10"
androidxComposeBom = "2023.09.02"
androidxActivityCompose = "1.7.2"
junitVersion = "4.13.2"
androidxTestRunnerVersion = "1.5.2"
androidxTestRulesVersion = "1.5.0"

[libraries]
androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "androidxComposeBom" }
androidx-compose-material3 = { group = "androidx.compose.material3", name = "material3" }
androidx-compose-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
androidx-compose-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
androidx-compose-ui-test-junit4 = { group = "androidx.compose.ui", name = "ui-test-junit4" }
androidx-compose-ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }
androidx-compose-ui-material-icons-extended = { group = "androidx.compose.material", name = "material-icons-extended" }
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "androidxActivityCompose" }
junit-junit = { group = "junit", name = "junit", version.ref = "junitVersion" }
androidx-test-runner = { group = "androidx.test", name="runner", version.ref = "androidxTestRunnerVersion" }
androidx-test-rules = { group = "androidx.test", name="rules", version.ref = "androidxTestRulesVersion" }

[bundles]
compose = ["androidx.compose.material3", "androidx.compose.ui.tooling.preview", "androidx.compose.ui.material.icons.extended"]
compose-debug = ["androidx.compose.ui.tooling", "androidx.compose.ui.test.manifest"]
testing = ["junit.junit"]
ui-testing = ["androidx.test.runner", "androidx.test.rules", "androidx.compose.ui.test.junit4"]

[plugins]
android-application = { id = "com.android.application", version.ref = "androidGradlePlugin" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlinVersion" }
