[versions]
androidGradlePlugin = "8.1.1"
kotlinVersion = "1.8.22"
androidxComposeBom = "2022.12.00"
activityCompose = "1.7.2"

[libraries]
androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "androidxComposeBom" }
androidx-compose-material3 = { group = "androidx.compose.material3", name = "material3" }
androidx-compose-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
androidx-compose-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
androidx-compose-ui-test-junit4 = { group = "androidx.compose.ui", name = "ui-test-junit4" }
androidx-compose-ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }
androidx-compose-ui-material-icons-extended = { group = "androidx.compose.material", name = "material-icons-extended" }
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activityCompose" }

[bundles]
compose = ["androidx.compose.material3", "androidx.compose.ui.tooling.preview", "androidx.compose.ui.material.icons.extended"]
compose-debug = ["androidx.compose.ui.tooling", "androidx.compose.ui.test.manifest"]
compose-android-test = ["androidx.compose.ui.test.junit4"]

[plugins]
android-application = { id = "com.android.application", version.ref = "androidGradlePlugin" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlinVersion" }
